-- 1. Masukkan posisi baru ke tabel posisi jika belum ada
INSERT IGNORE INTO `posisi` (`nama`) VALUES ('ADMIN MARKETING & SOSMED');

-- 2. Hapus data lama posisi ini jika ada agar tidak double
DELETE FROM `bank_soal_sesi5` WHERE `posisi` = 'ADMIN MARKETING & SOSMED';

-- 3. Masukkan 5 Studi Kasus ADMIN MARKETING & SOSMED ke bank_soal_sesi5 (Format Rapih dengan <br> & <strong>)
INSERT INTO `bank_soal_sesi5` (`posisi`, `tipe`, `judul`, `deskripsi`, `pertanyaan`) VALUES
('ADMIN MARKETING & SOSMED', 'studi_kasus', 'Studi Kasus 1: Konten Banyak, Engagement Menurun (Fokus: Analisis Sosial Media & Riset Audiens)', 'Dalam 3 bulan terakhir, akun sosial media perusahaan rutin mengunggah konten sebanyak 4–5 kali dalam seminggu (total ~50 konten/bulan). Meskipun konsisten, performa akun mengalami penurunan signifikan:<br>• <strong>Engagement Rate (ER):</strong> Anjlok dari 3,8% menjadi 0,9%.<br>• <strong>Keterlibatan Audiens:</strong> Rata-rata likes turun 60%, comments turun 75%, dan shares/saves merosot hingga 80%.<br>• <strong>Pertumbuhan Audiens:</strong> Penambahan followers baru minus (net gain -150 followers/bulan akibat unfollow).<br>• <strong>Jangkauan vs Interaksi:</strong> Reach harian relatif stabil (rata-rata 15.000–20.000 impressions per konten viral/Reels), namun conversion rate ke interaksi maupun leads hampir 0% (kurang dari 5 DMs atau klik link bio per bulan).', '[\"1. Berdasarkan kondisi tersebut, menurut Anda apa kemungkinan penyebab engagement sosial media menurun meskipun perusahaan tetap rutin membuat konten?\",\"2. Data apa saja yang harus Anda kumpulkan dan analisis untuk mengetahui jenis konten, waktu posting, serta karakteristik audiens yang paling efektif?\",\"3. Jika diberi waktu 1 bulan untuk memperbaiki performa sosial media, strategi konten apa yang akan Anda lakukan dan bagaimana cara mengukur keberhasilannya?\"]'),

('ADMIN MARKETING & SOSMED', 'studi_kasus', 'Studi Kasus 2: Konten Kompetitor Lebih Menarik (Fokus: Analisis Kompetitor & Strategi Konten)', 'Anda menemukan bahwa kompetitor yang menjual produk sejenis memiliki jumlah followers dan engagement yang jauh lebih tinggi. Konten mereka sering mendapatkan banyak komentar dan dibagikan oleh audiens. Tim Marketing meminta Anda mencari tahu mengapa konten kompetitor lebih menarik dibandingkan konten perusahaan.', '[\"1. Secara objektif, aspek apa saja yang harus Anda bandingkan dari sosial media perusahaan dengan kompetitor untuk mengetahui kelebihan dan kelemahan masing-masing?\",\"2. Jika ternyata kompetitor lebih unggul dalam konsep visual, copywriting, dan konsistensi konten, perbaikan seperti apa yang akan Anda usulkan tanpa sekadar meniru konten mereka?\",\"3. Mengapa Admin Marketing & Sosmed tidak boleh langsung mengikuti semua tren atau konten viral tanpa melakukan analisis kesesuaian dengan target pasar dan citra perusahaan?\"]'),

('ADMIN MARKETING & SOSMED', 'studi_kasus', 'Studi Kasus 3: Leads dari Sosial Media Tidak Berkualitas (Fokus: Leads, Respons Admin & Follow-Up)', 'Perusahaan mulai mendapatkan banyak pertanyaan melalui WhatsApp dan Direct Message (DM) setelah menjalankan beberapa promosi di sosial media. Namun, sebagian besar hanya bertanya harga, tidak memberikan informasi kebutuhan, dan kemudian tidak merespons kembali. Tim Sales mengeluhkan bahwa leads dari sosial media banyak tetapi tingkat konversinya rendah.', '[\"1. Menurut Anda, apa kemungkinan penyebab banyaknya leads tetapi sedikit yang menjadi calon pelanggan potensial?\",\"2. Informasi apa saja yang harus dicatat oleh Admin Marketing & Sosmed dari setiap leads agar dapat membantu tim Sales melakukan follow-up dengan lebih tepat?\",\"3. Buatlah contoh alur respons Admin Marketing & Sosmed mulai dari pelanggan pertama kali menghubungi melalui DM sampai leads tersebut diserahkan kepada tim Sales.\"]'),

('ADMIN MARKETING & SOSMED', 'studi_kasus', 'Studi Kasus 4: Membuat Konten Produk yang Tidak Membosankan (Fokus: Content Planning, Copywriting & Branding)', 'Perusahaan memiliki banyak produk dengan spesifikasi dan keunggulan teknis yang berbeda. Selama ini sosial media perusahaan hanya menampilkan foto produk, spesifikasi, ukuran, dan harga. Konten terlihat monoton dan audiens kurang tertarik untuk membaca sampai selesai.', '[\"1. Mengapa hanya menampilkan spesifikasi dan harga produk tidak cukup untuk membuat calon pelanggan tertarik?\",\"2. Rancang 3 informasi utama yang harus ditonjolkan dalam sebuah konten produk agar calon pelanggan memahami manfaat produk dan tertarik untuk mencari informasi lebih lanjut.\",\"3. Jika Anda diminta membuat content plan selama 1 minggu, bagaimana pembagian jenis konten yang akan Anda buat agar tidak hanya berisi promosi produk?\"]'),

('ADMIN MARKETING & SOSMED', 'studi_kasus', 'Studi Kasus 5: Konten Viral yang Menimbulkan Salah Persepsi (Fokus: Social Media Crisis & Public Relations)', 'Sebuah video tentang produk perusahaan yang diunggah oleh pihak luar menjadi viral dan menimbulkan berbagai komentar negatif. Sebagian komentar menyebut produk perusahaan tidak sesuai dengan informasi yang diberikan. Meskipun informasi tersebut belum terbukti benar, jumlah komentar dan share terus meningkat. Beberapa calon pelanggan mulai mempertanyakan kredibilitas perusahaan melalui DM.', '[\"1. Apa risiko bagi citra perusahaan jika isu tersebut dibiarkan tanpa klarifikasi?\",\"2. Apa langkah yang Anda lakukan untuk memverifikasi isu dan menentukan respons perusahaan di sosial media?\",\"3. Bagaimana Anda membuat klarifikasi agar informasi tersampaikan dengan jelas tanpa terkesan defensif atau menyalahkan pihak lain?\"]');
